### ISSUE TITLE
Guider PiP 설치 후 참조시 오류

### ISSUE THREAD

**Issue by yangsso** [iipeace/guider#108]
Guider PiP 설치 후 참조시 오류

@iipeace

**Comment by iipeace** [comment]
@yangsso,
please try again and share error log :)

**Comment by iipeace** [comment]
@yangsso,
could you check it again?

**Comment by biofool** [comment]
sudo pipx/venvs/guider/bin/guider  iorec

   _____       _     _
  / ____|     (_)   | |
 | |  __ _   _ _  __| | ___ _ __
 | | |_ | | | | |/ _` |/ _ \ '__|
 | |__| | |_| | | (_| |  __/ |
  \_____|\__,_|_|\__,_|\___|_|  ver_3.9.8_240429 on python_3.11


[INFO] changed the CPU scheduling priority for guider(380680) to -20[C]

[INFO] <THREAD MODE>

[INFO] enabled runtime options [ X64 ENCODE PRINT BLOCK LATENCY COMP ]

[STEP] prepare for recording... [ STOP(Ctrl+c), MARK(Ctrl+\) ]

[INFO] clear trace buffer... [done]

[STEP] start recording... [ STOP(Ctrl+c), MARK(Ctrl+\) ]
^\
[INFO] wrote 'MARK' event
^C
[STEP] finished recording for 10.170 sec

[STEP] ready to save and analyze... [ STOP(Ctrl+c) ]

[INFO] use 192.168.68.77:5555(UDP) as local address

[INFO] enabled analysis options [ LATENCY BLOCK PRINT ]

[STEP] start analyzing... [ STOP(Ctrl+c) ]
[STEP] start analyzing... [ STOP(Ctrl+c) ]
  0% |
[ERROR] please report '/var/log/guider/guider.err' to https://github.com/iipeace/guider/issues
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/kkron/projects/Vigilent/src/guider/guider/__main__.py", line 7, in <module>
    main(args=None)
  File "/home/kkron/projects/Vigilent/src/guider/guider/guider.py", line 145119, in main
    TaskAnalyzer(SysMgr.inputFile).printUsage()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kkron/projects/Vigilent/src/guider/guider/guider.py", line 110318, in __init__
    time = self.parse(log)
           ^^^^^^^^^^^^^^^
  File "/home/kkron/projects/Vigilent/src/guider/guider/guider.py", line 130952, in parse
    self.handleUserEvent(d["event"], time)
  File "/home/kkron/projects/Vigilent/src/guider/guider/guider.py", line 127937, in handleUserEvent
    EventAnalyzer.addEvent(time, event)
  File "/home/kkron/projects/Vigilent/src/guider/guider/guider.py", line 98534, in addEvent
    __builtins__.sum(t[0] == ID for t in eventData[name]["list"])
    ^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'sum'

**Comment by iipeace** [comment]
@biofool could you check latest commit @master?
