### ISSUE TITLE
 ERROR in app: Exception on /dataset [GET]

### ISSUE THREAD

**Issue by KangWooJin** [iipeace/guider#173]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/user/IdeaProjects/guider/agent/monitoring/controllers.py", line 29, in get
    count = Data.objects.count()
  File "/usr/local/lib/python3.7/site-packages/mongoengine/queryset/manager.py", line 37, in __get__
    queryset = queryset_class(owner, owner._get_collection())
  File "/usr/local/lib/python3.7/site-packages/mongoengine/document.py", line 207, in _get_collection
    db.client.is_primary:
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1006, in is_primary
    return self._server_property('is_writable')
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 831, in _server_property
    writable_server_selector)
  File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 231, in select_server
    address))
  File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 189, in select_servers
    selector, server_timeout, address)
  File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 205, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 61] Connection refused
```

**Comment by iipeace** [comment]
@Agrajak
