### ISSUE TITLE
Flask에서 request_start()처리시 오류 발생

### ISSUE THREAD

**Issue by Agrajak** [iipeace/guider#62]
Issue #59 에 언급된 CORS 이슈를 해결하기 위해서 
```python
socketio = SocketIO(app, cors_allowed_origins='*')
```
로 수정하고 프로그램을 돌려보는데 하단의 오류가 발생했습니다.

`
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/agrajak/.local/lib/python2.7/site-packages/socketio/server.py", line 648, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/home/agrajak/.local/lib/python2.7/site-packages/socketio/server.py", line 677, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/home/agrajak/.local/lib/python2.7/site-packages/flask_socketio/__init__.py", line 284, in _handler
    *args)
  File "/home/agrajak/.local/lib/python2.7/site-packages/flask_socketio/__init__.py", line 698, in _handle_event
    ret = handler(*args)
  File "__init__.py", line 125, in request_start
    msg['timestamp'] = timestamp
TypeError: 'unicode' object does not support item assignment
`
```
// guider/guider-vue/src/Socket.IO.vue
this.$socket.emit('request_start', String(timestamp), this.targetAddr)
```
혹시 String을 유니코드로 인식해서 발생하나 싶어서 timestamp.getTime()으로 int값을 넘겨주어 보았는데도 똑같은 오류가 발생하네요..

**Comment by iipeace** [comment]
제가 수정한 내용이 잘 반영되었는지 최신 src에서 다시 확인해주실래요~?? :)
